version: '3'

services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql8.0.31
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=store
      - TZ=Asia/Seoul
    command: [ '--init-file=/data/application/mysql-init.sql', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    ports:
      - "3306:3306"
    networks:
      - storenet
    restart: always
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql-init.sql:/data/application/mysql-init.sql

networks:
  storenet:
    driver: bridge