springdoc:
  packages-to-scan: com.platform.api
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    path: /api/public/api-docs/json
  swagger-ui:
    path: /public/swagger-ui
    disable-swagger-default-url: true #기본 Swagger Petstore URL을 어떻게 비활성화
    display-request-duration: true # API 응답 시간의 표시
    operations-sorter: alpha  # Tag의 정렬 기준을 설정한다. (alpha : 알파벳순)