
server:
  port: 8080

spring:
  profiles:
    active: local
    group:
      local: base, datasource-base, web-base

jwt:
  expiration:
    period: 1252800000 # 14 * 24 * 60 * 60 * 1000 + 12 * 60 * 60 * 1000
    #    period: 60000 # 60 * 1000 : 테스트용 (1분)
    renew-before: 432000000 # 5 * 24 * 60 * 60 * 1000
    #    renew-before: 20000 # 20 * 1000 : 테스트용 (20초)
